name: check_benchopt_branch
on:
  pull_request:
    branches:
      - main

jobs:
  check_benchopt_branch:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Check benchopt branch used in test
      run: python .github/scripts/check_benchopt_branch.py
