name: check_benchopt_branch
on:
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check benchopt branch used in test
      run: .github/workflows/check_benchopt_branch.py
      shell: python
