name: checks
on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      env:
        BENCHOPT_BRANCH: benchopt:master
      run: |
        eval "$(conda shell.bash hook)"
        conda activate base
        # make sure we have the latest version of pip
        # to correctly install benchopt in sub conda env
        pip install --upgrade pip

        # Get the correct branch from benchopt
        USER=${BENCHOPT_BRANCH%:*}
        BRANCH=${BENCHOPT_BRANCH##*:}
        pip install -U git+https://github.com/$USER/benchopt@$BRANCH

    - name: Test
      env:
          BENCHO_DEBUG: 1
      run: |
        eval "$(conda shell.bash hook)"
        conda activate base
        benchopt test . --env-name bench_test_env -vl
        benchopt test . --env-name bench_test_env -vl --skip-install


  linter-flake8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
